/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle.project;

import gradle.project.mapper.UserMapper;
import gradle.project.dto.UserDTO;
import gradle.project.model.UserModel;

public class Main {
    
    private static final UserMapper mapper = Mappers.getMapper(UserMapper.class);
    public static void main(String[] args) {

        var model = new UserModel();
        model.setCode(1);
        model.setUserName("John Doe");

        var dto = mapper.toDto(model);
        System.out.println(dto);

    }
}
